# A brief introduction to nonlinear programming

BAZON Flavien

https://drive.google.com/file/d/1yv56ek9qgNZR2f7rDZPvrEIcBgG_WZum/view

## 1 Unconstrained optimization

### Task 1

In [2]:
import numpy as np

def f1(x):
    x1, x2 = x[0], x[1]
    return x1**2 + x2**2 - 2*x1*x2

def f2(x):
    x1, x2 = x[0], x[1]
    return 10*(x2-x1**2)**2 + (1-x1)**2

def f3(x):
    return np.dot(x, x) * 0.5

def oracle_f1(x, mode=2):
    x1, x2 = x[0], x[1]
    if mode == 1:
        return f1(x)
    if mode == 3:
        g = np.array([2*x1 - 2*x2, 2*x2 - 2*x1])
        return g
    if mode == 2:
        f = f1(x)
        g = np.array([2*x1 - 2*x2, 2*x2 - 2*x1])
        return f, g

def oracle_f2(x, mode=2):
    x1, x2 = x[0], x[1]
    if mode == 1:
        return f2(x)
    if mode == 3:
        g = np.array([-40*x1*(x2-x1**2) - 2*(1-x1),
                      20*(x2-x1**2)])
        return g
    if mode == 2:
        f = f2(x)
        g = np.array([-40*x1*(x2-x1**2) - 2*(1-x1),
                      20*(x2-x1**2)])
        return f, g

def oracle_f3(x, mode=2):
    if mode == 1:
        return f3(x)
    if mode == 3:
        g = x.copy()
        return g
    if mode == 2:
        f = f3(x)
        g = x.copy()
        return f, g


In [3]:
oracle_f1(np.array([np.array([25.0,4.0]), np.array([1.0,1.0])]))

(array([576.,   9.]),
 array([[ 48.,   6.],
        [-48.,  -6.]]))

In [4]:
oracle_f3(np.array([15,1856],dtype=float))

(np.float64(1722480.5), array([  15., 1856.]))

### Task 2

In [7]:
def gradient_method(oracle, x0, step_size=0.01, max_iter=1000, tol=1e-6):
    x = np.array(x0, dtype=float)
    history = [x.copy()]
    for i in range(max_iter):
        f, g = oracle(x)
        print("f", f, "x", x, "g", g)
        x_new = x - step_size * g
        history.append(x_new.copy())
        if np.linalg.norm(g) < tol:
            break
        x = x_new
    return x, history
    print(f,g)

# gradient_method(oracle_f2, np.array([np.array([25.0,4.0]), np.array([1.0,1.0])]), step_size=0.6)
gradient_method(oracle_f1, [-2,2], step_size=0.05)

#cas 2 si point de depart trop loins le gradient est enorme donc il nous degage sur un point enore plus enorme, c une decente de grad de merde

f 16.0 x [-2.  2.] g [-8.  8.]
f 10.240000000000002 x [-1.6  1.6] g [-6.4  6.4]
f 6.5536 x [-1.28  1.28] g [-5.12  5.12]
f 4.194304 x [-1.024  1.024] g [-4.096  4.096]
f 2.68435456 x [-0.8192  0.8192] g [-3.2768  3.2768]
f 1.7179869184000003 x [-0.65536  0.65536] g [-2.62144  2.62144]
f 1.0995116277760004 x [-0.524288  0.524288] g [-2.097152  2.097152]
f 0.7036874417766403 x [-0.4194304  0.4194304] g [-1.6777216  1.6777216]
f 0.45035996273704976 x [-0.33554432  0.33554432] g [-1.34217728  1.34217728]
f 0.2882303761517119 x [-0.26843546  0.26843546] g [-1.07374182  1.07374182]
f 0.18446744073709562 x [-0.21474836  0.21474836] g [-0.85899346  0.85899346]
f 0.11805916207174119 x [-0.17179869  0.17179869] g [-0.68719477  0.68719477]
f 0.07555786372591435 x [-0.13743895  0.13743895] g [-0.54975581  0.54975581]
f 0.04835703278458518 x [-0.10995116  0.10995116] g [-0.43980465  0.43980465]
f 0.030948500982134516 x [-0.08796093  0.08796093] g [-0.35184372  0.35184372]
f 0.019807040628566086 x [

(array([-1.68499667e-07,  1.68499667e-07]),
 [array([-2.,  2.]),
  array([-1.6,  1.6]),
  array([-1.28,  1.28]),
  array([-1.024,  1.024]),
  array([-0.8192,  0.8192]),
  array([-0.65536,  0.65536]),
  array([-0.524288,  0.524288]),
  array([-0.4194304,  0.4194304]),
  array([-0.33554432,  0.33554432]),
  array([-0.26843546,  0.26843546]),
  array([-0.21474836,  0.21474836]),
  array([-0.17179869,  0.17179869]),
  array([-0.13743895,  0.13743895]),
  array([-0.10995116,  0.10995116]),
  array([-0.08796093,  0.08796093]),
  array([-0.07036874,  0.07036874]),
  array([-0.056295,  0.056295]),
  array([-0.045036,  0.045036]),
  array([-0.0360288,  0.0360288]),
  array([-0.02882304,  0.02882304]),
  array([-0.02305843,  0.02305843]),
  array([-0.01844674,  0.01844674]),
  array([-0.0147574,  0.0147574]),
  array([-0.01180592,  0.01180592]),
  array([-0.00944473,  0.00944473]),
  array([-0.00755579,  0.00755579]),
  array([-0.00604463,  0.00604463]),
  array([-0.0048357,  0.0048357]),
  arra

In [6]:
#armijo

def armijo(oracle, x0, t0=1, max_iter=100, tol=1e-6, m=0.001, theta=0.2):
    x=np.array(x0, dtype=float)
    for i in range(max_iter):
        f, g = oracle(x)
        t = t0
        while True:
            x_new = x - t * g
            f_new, _ = oracle(x_new)
            if f_new <= f - m * t * np.dot(g, g):
                break
            t *= theta
        x = x_new
        print("f", f, "x", x, "g", g, "t", t, "\n")
        if np.linalg.norm(f) < tol:
            break
    return "fini"

armijo(oracle_f2, np.array([25.0,4.0]), t0=1)

f 3856986.0 x [-14.747072   4.79488 ] g [621048. -12420.] t 6.400000000000002e-05 

f 452581.1222375602 x [-6.71580647  5.067112  ] g [-125488.52393388   -4253.62505146] t 6.400000000000002e-05 

f 16087.501493007623 x [-3.26937153  5.32333565] g [-10770.10918622   -800.69889031] t 0.00032000000000000013 

f 306.10855789673855 x [2.412271   6.18180838] g [-710.20531604 -107.30909088] t 0.008000000000000002 

f 3.31043578128886 x [2.4637561  6.17020015] g [-32.17818556   7.25513998] t 0.0016000000000000005 

f 2.242794118166516 x [2.47485684 6.16699676] g [-6.93796322  2.00212095] t 0.0016000000000000005 

f 2.192910284397523 x [2.47680244 6.16565019] g [-1.21600399  0.84160781] t 0.0016000000000000005 

f 2.1906174582271594 x [2.47782261 6.16067421] g [-0.12752129  0.62199676] t 0.008000000000000002 

f 2.188398834899397 x [2.47643477 6.15999999] g [0.86740548 0.42138605] t 0.0016000000000000005 

f 2.187296607108535 x [2.46637513 6.13818332] g [0.25149082 0.54541689] t 0.0400000000000

'fini'

## 2

fonction convexe
donc min local = min global
sans contrainte: condiiton optimalité: grad = 0



In [1]:
print(oracle_f2(np.array([1.0,1.0]), mode=2))

NameError: name 'oracle_f2' is not defined

In [1]:
print(oracle_f1(np.array([1.0,1.0]), mode=2))

NameError: name 'oracle_f1' is not defined